name: golden_toolkit
description: Common patterns for screenshot-based widget testing using Goldens.
version: 0.13.0
homepage: https://github.com/eBay/flutter_glove_box/
repository: https://github.com/eBay/flutter_glove_box/tree/master/packages/golden_toolkit
issue_tracker: https://github.com/eBay/flutter_glove_box/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_lints: ^1.0.4
  sample_dependency:
    path: test/sample_dependency
  test_api: ^0.4.2

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf
